/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BoolCheckbox: typeof import('./src/components/UI/BoolCheckbox.vue')['default']
    BreadCrumbs: typeof import('./src/components/UI/BreadCrumbs.vue')['default']
    Button: typeof import('./src/components/UI/Button.vue')['default']
    CardColumn: typeof import('./src/components/CardColumn/index.vue')['default']
    ChangePerformerCol: typeof import('./src/components/UserPermissionHistoryTable/ChangePerformerCol.vue')['default']
    Chip: typeof import('./src/components/UI/Chip.vue')['default']
    ConfirmDialogText: typeof import('./src/components/ManagePermissionsTable/ConfirmDialogText.vue')['default']
    DateCol: typeof import('./src/components/UserPermissionHistoryTable/DateCol.vue')['default']
    DatePicker: typeof import('./src/components/DatePicker.vue')['default']
    DelegatedAdminSection: typeof import('./src/components/AddPermissions/DelegatedAdminSection.vue')['default']
    Divider: typeof import('./src/components/UI/Divider.vue')['default']
    Dropdown: typeof import('./src/components/UI/Dropdown.vue')['default']
    ErrorText: typeof import('./src/components/UI/ErrorText.vue')['default']
    FailedGrantAppUsersNtfnTemplate: typeof import('./src/components/NotificationContent/FailedGrantAppUsersNtfnTemplate.vue')['default']
    ForestClientAddTable: typeof import('./src/components/AddPermissions/ForestClientAddTable.vue')['default']
    ForestClientSelectTable: typeof import('./src/components/AddPermissions/ForestClientSelectTable.vue')['default']
    HelperText: typeof import('./src/components/UI/HelperText.vue')['default']
    InputSkeleton: typeof import('./src/components/Skeletons/InputSkeleton.vue')['default']
    Label: typeof import('./src/components/UI/Label.vue')['default']
    ManagePermissionsTable: typeof import('./src/components/ManagePermissionsTable/index.vue')['default']
    MyPermissionsTable: typeof import('./src/components/MyPermissionsTable/index.vue')['default']
    NewUserTag: typeof import('./src/components/ManagePermissionsTable/NewUserTag.vue')['default']
    NotificationMessage: typeof import('./src/components/UI/NotificationMessage.vue')['default']
    OrganizationList: typeof import('./src/components/UserPermissionHistoryTable/OrganizationList.vue')['default']
    PageTitle: typeof import('./src/components/UI/PageTitle.vue')['default']
    PermissionDetailsCol: typeof import('./src/components/UserPermissionHistoryTable/PermissionDetailsCol.vue')['default']
    PSkeleton: typeof import('./src/components/Skeletons/PSkeleton.vue')['default']
    RoleSelectTable: typeof import('./src/components/AddPermissions/RoleSelectTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SccssGrantAppUsersNtfnTemplate: typeof import('./src/components/NotificationContent/SccssGrantAppUsersNtfnTemplate.vue')['default']
    ServiceUnavailableNtfnTemplate: typeof import('./src/components/NotificationContent/ServiceUnavailableNtfnTemplate.vue')['default']
    Spinner: typeof import('./src/components/UI/Spinner.vue')['default']
    StepContainer: typeof import('./src/components/UI/StepContainer.vue')['default']
    SubsectionTitle: typeof import('./src/components/UI/SubsectionTitle.vue')['default']
    TableHeaderTitle: typeof import('./src/components/Table/TableHeaderTitle.vue')['default']
    TablePlaceholder: typeof import('./src/components/ManagePermissionsTable/TablePlaceholder.vue')['default']
    TableSkeleton: typeof import('./src/components/Skeletons/TableSkeleton.vue')['default']
    TableToolbar: typeof import('./src/components/Table/TableToolbar.vue')['default']
    TermsAndConditions: typeof import('./src/components/TermsAndConditions.vue')['default']
    UserPermissionHistoryTable: typeof import('./src/components/UserPermissionHistoryTable/index.vue')['default']
    UserSearch: typeof import('./src/components/Search/UserSearch.vue')['default']
    UserSearchResultsDialog: typeof import('./src/components/Search/UserSearchResultsDialog.vue')['default']
    UserSearchSelectedTable: typeof import('./src/components/Search/UserSearchSelectedTable.vue')['default']
    UserSummaryCard: typeof import('./src/components/UserSummaryCard/index.vue')['default']
  }
}
