-- FAM baseline schema.
--
-- Replaces the 95 migrations inherited from the Python service. Those recorded
-- how FAM's own tables grew and were then largely dismantled: applications,
-- roles and role assignments moved to CSS, and V94 dropped the twenty tables
-- that held them. Replaying that history onto an empty database would create
-- sixteen tables in order to drop them again, so this states the end result
-- instead.
--
-- Four tables remain, and each is here for a reason CSS cannot cover:
--
--   fam_user / fam_user_type_code
--     Who has signed in. FAM provisions a row at login because a BC Gov SSO
--     realm cannot run application code at token time, so the identity has to
--     be resolved and stored somewhere.
--
--   fam_privilege_change_audit / fam_privilege_change_type
--     Who granted what to whom. CSS keeps no history of role assignments, so
--     if it is not recorded here it is recorded nowhere.
--
-- Deliberately absent: roles, role assignments, applications, delegated admin
-- and forest client tables. All are CSS or the Forest Client API now, and a
-- column here would be a second, staler copy of them.
--
-- The entity classes are validated against this schema at start-up
-- (`ddl-auto: validate`), so a mismatch fails the application at boot rather
-- than at the first write. Any change here needs the matching entity change.

-- Normally a no-op: dba/01_create_roles.sql creates the schema with
-- AUTHORIZATION fam_owner, and this migration runs afterwards. It is here so a
-- throwaway database works without the DBA scripts.
--
-- If the schema does NOT already exist, it is created owned by whoever runs
-- Flyway. That matters: dba/02 attaches ALTER DEFAULT PRIVILEGES FOR ROLE
-- fam_owner, which only covers tables fam_owner creates. Run the DBA scripts
-- first in any environment that has them.
CREATE SCHEMA IF NOT EXISTS app_fam;

-- ---------------------------------------------------------------------------
-- Code tables
-- ---------------------------------------------------------------------------

CREATE TABLE app_fam.fam_user_type_code (
    user_type_code  VARCHAR(2)   NOT NULL,
    description     VARCHAR(100),
    effective_date  TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    expiry_date     TIMESTAMP(6) WITH TIME ZONE,
    update_date     TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT fam_user_type_code_pk PRIMARY KEY (user_type_code)
);

COMMENT ON TABLE app_fam.fam_user_type_code IS
    'The identity provider a user signs in through.';

INSERT INTO app_fam.fam_user_type_code (user_type_code, description) VALUES
    ('I',  'IDIR'),
    ('B',  'Business BCeID'),
    ('CD', 'BCSC (Dev)'),
    ('CT', 'BCSC (Test)'),
    ('CP', 'BCSC');

-- The four values PrivilegeChangeType can hold. CREATE_ROLE is eleven
-- characters, which is why the code column is 20 rather than the 10 the
-- original table used.
CREATE TABLE app_fam.fam_privilege_change_type (
    privilege_change_type_code  VARCHAR(20)  NOT NULL,
    description                 VARCHAR(100) NOT NULL,
    effective_date              TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    expiry_date                 TIMESTAMP(6) WITH TIME ZONE,
    update_date                 TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT fam_privilege_change_type_pk PRIMARY KEY (privilege_change_type_code)
);

COMMENT ON TABLE app_fam.fam_privilege_change_type IS
    'Kinds of change recorded in fam_privilege_change_audit: granting, revoking or updating a user''s access, and defining a role an application offers.';

INSERT INTO app_fam.fam_privilege_change_type (privilege_change_type_code, description) VALUES
    ('GRANT',       'Role added'),
    ('REVOKE',      'Role revoked'),
    ('UPDATE',      'Role updated'),
    ('CREATE_ROLE', 'Role created');

-- ---------------------------------------------------------------------------
-- Users
-- ---------------------------------------------------------------------------

CREATE TABLE app_fam.fam_user (
    user_id        BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    user_type_code VARCHAR(2)   NOT NULL,
    user_name      VARCHAR(100) NOT NULL,
    user_guid      VARCHAR(32),
    business_guid  VARCHAR(32),
    oidc_user_id   VARCHAR(100),
    first_name     VARCHAR(50),
    last_name      VARCHAR(50),
    email          VARCHAR(250),
    create_user    VARCHAR(100) NOT NULL,
    create_date    TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    update_user    VARCHAR(100),
    update_date    TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT fam_user_pk PRIMARY KEY (user_id),
    CONSTRAINT fam_user_type_fk FOREIGN KEY (user_type_code)
        REFERENCES app_fam.fam_user_type_code (user_type_code)
);

COMMENT ON TABLE app_fam.fam_user IS
    'A person who has signed in to FAM. Created at login, refreshed from the identity directory.';
COMMENT ON COLUMN app_fam.fam_user.user_guid IS
    'The identity provider''s GUID for this user. What CSS assignments are keyed on, so it is the durable identifier - user_name can be reissued.';
COMMENT ON COLUMN app_fam.fam_user.business_guid IS
    'The organisation a Business BCeID user belongs to. Null for IDIR. What the same-organisation rule compares against.';
COMMENT ON COLUMN app_fam.fam_user.oidc_user_id IS
    'The OIDC subject claim from BC Gov SSO. Named cognito_user_id before this baseline, from the Cognito era.';

-- Provisioning looks a user up by (type, GUID) and falls back to (type, name),
-- both case-insensitively; these serve those lookups and stop a concurrent
-- login creating the same person twice.
CREATE UNIQUE INDEX fam_user_type_guid_uk
    ON app_fam.fam_user (user_type_code, UPPER(user_guid));
CREATE UNIQUE INDEX fam_user_type_name_uk
    ON app_fam.fam_user (user_type_code, UPPER(user_name));

-- Every authenticated request resolves the requester by subject claim.
CREATE INDEX fam_user_oidc_user_id_idx
    ON app_fam.fam_user (oidc_user_id);

-- ---------------------------------------------------------------------------
-- Privilege change audit
-- ---------------------------------------------------------------------------

-- Append-only, and deliberately free of foreign keys into fam_user. An audit
-- row that points at a mutable operational row is only as durable as that row:
-- removing a user would break the history. The identifiers are recorded
-- directly, and the performer and privilege are stored as snapshots, so the
-- trail stays truthful after users are renamed or roles redefined.
CREATE TABLE app_fam.fam_privilege_change_audit (
    privilege_change_audit_id     BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    css_integration_id            INTEGER,
    css_environment               VARCHAR(10),
    change_date                   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    change_performer_user_details JSONB        NOT NULL,
    performer_user_guid           VARCHAR(32),
    target_user_guid              VARCHAR(32),
    target_user_type_code         VARCHAR(2),
    privilege_change_type_code    VARCHAR(20)  NOT NULL,
    privilege_details             JSONB        NOT NULL,
    create_user                   VARCHAR(100) NOT NULL,
    create_date                   TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT fam_privilege_change_audit_pk PRIMARY KEY (privilege_change_audit_id),
    CONSTRAINT fam_privilege_change_type_fk FOREIGN KEY (privilege_change_type_code)
        REFERENCES app_fam.fam_privilege_change_type (privilege_change_type_code)
);

COMMENT ON TABLE app_fam.fam_privilege_change_audit IS
    'Append-only record of privilege changes. CSS keeps no history of its own, so this is the only account of who granted or revoked what.';
COMMENT ON COLUMN app_fam.fam_privilege_change_audit.css_integration_id IS
    'The CSS integration the change was made against. With css_environment this identifies what FAM calls an application.';
COMMENT ON COLUMN app_fam.fam_privilege_change_audit.change_date IS
    'When the change happened. Distinct from create_date, which is when this row was written.';
COMMENT ON COLUMN app_fam.fam_privilege_change_audit.performer_user_guid IS
    'Who made the change. Null when a system process did.';
COMMENT ON COLUMN app_fam.fam_privilege_change_audit.target_user_guid IS
    'Who the change was made to. Null for a change with no target user, such as CREATE_ROLE.';
COMMENT ON COLUMN app_fam.fam_privilege_change_audit.privilege_details IS
    'What changed, as JSON. The shape follows the change type: a grant or revocation describes the role and scopes; CREATE_ROLE describes the role that was defined.';

-- History is read for one user within one application, most recent first. The
-- GUID is compared case-insensitively, so the index has to be too.
CREATE INDEX fam_privilege_change_audit_history_idx
    ON app_fam.fam_privilege_change_audit
       (css_integration_id, css_environment, UPPER(target_user_guid), change_date DESC);
