-- Intentionally empty.
--
-- Upstream this migration wiped fam_user / fam_user_role_xref and then seeded
-- five named BC Gov IDIR accounts as FAM_ACCESS_ADMIN and FOM_ACCESS_ADMIN.
-- Those grants did not stay in fam_user_role_xref: V34 copied them into
-- fam_application_admin and V38 deleted the FAM roles behind them, so by V93
-- the five accounts were full application admins of FAM and FOM.
--
-- Carrying that forward would have made five people admins of this deployment
-- on day one, inherited rather than chosen, with no later migration revoking
-- them. Who administers FAM here is a decision for this project, made through
-- the admin surface (or a deliberate site-specific migration) - not something
-- to inherit from another organisation's history.
--
-- Dropping the seed data also drops the unconditional DELETE that preceded it,
-- which would otherwise empty both tables on any database that was not brand
-- new.
--
-- V34 and V38 still run; with nothing to migrate they are no-ops (INSERT ...
-- SELECT over an empty result, DELETE matching no rows).
--
-- Local development gets its own admin from migrations/local_sql, which never
-- runs in a deployed environment.
--
-- Kept as a placeholder so the migration version sequence stays contiguous.
