package ca.bc.gov.nrs.fam.entity;

import jakarta.persistence.Column;
import jakarta.persistence.MappedSuperclass;
import jakarta.persistence.PrePersist;
import java.time.LocalDateTime;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

/**
 * The four audit columns carried by every FAM table, including the code tables.
 *
 * <p>All four are {@code timestamp(6)} without a time zone, and all four are
 * {@code NOT NULL}. The containers run with {@code TZ=America/Vancouver}, so
 * stored values are BC local time and line up with the application's own logs.
 *
 * <p>{@code create_user} and {@code update_user} hold a prefixed identity -
 * {@code IDIR\<guid>} - or {@code system}; see
 * {@link ca.bc.gov.nrs.fam.security.AuditUser}. They are names, not foreign keys.
 *
 * <p>Timestamps are generated by Hibernate rather than left to the column
 * defaults, matching SQLAlchemy's {@code onupdate=func.now()} behaviour where
 * the ORM, not the database, stamped updates.
 */
@Getter
@Setter
@MappedSuperclass
public abstract class AuditedEntity {

  @Column(name = "create_user", nullable = false, length = 100)
  private String createUser;

  @CreationTimestamp
  @Column(name = "create_date", nullable = false)
  private LocalDateTime createDate;

  @Column(name = "update_user", nullable = false, length = 100)
  private String updateUser;

  @UpdateTimestamp
  @Column(name = "update_date", nullable = false)
  private LocalDateTime updateDate;

  /**
   * A newly created row is "last updated" by whoever created it.
   *
   * <p>Callers set {@code create_user} and have no reason to think about
   * {@code update_user} on an insert, so filling it here is what makes the
   * {@code NOT NULL} safe to rely on. The alternative - leaving it null until the
   * first update - encodes "never updated" as an absence, which is invisible in
   * the data and easily misread as a missing value.
   */
  @PrePersist
  void defaultUpdateUserToCreator() {
    if (updateUser == null) {
      updateUser = createUser;
    }
  }
}
