package ca.bc.gov.nrs.fam.entity;

import jakarta.persistence.Column;
import jakarta.persistence.MappedSuperclass;
import java.time.OffsetDateTime;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

/**
 * The four audit columns carried by every FAM business table.
 *
 * <p>All four are {@code timestamptz(6)} after V20 converted the schema away
 * from naive timestamps. {@code create_user} and {@code update_user} hold a user
 * name or a proxy account name, not a foreign key.
 *
 * <p>Timestamps are generated by Hibernate rather than left to the column
 * defaults, matching SQLAlchemy's {@code onupdate=func.now()} behaviour where
 * the ORM, not the database, stamped updates.
 */
@Getter
@Setter
@MappedSuperclass
public abstract class AuditedEntity {

  @Column(name = "create_user", nullable = false, length = 100)
  private String createUser;

  @CreationTimestamp
  @Column(name = "create_date", nullable = false)
  private OffsetDateTime createDate;

  @Column(name = "update_user", length = 100)
  private String updateUser;

  @UpdateTimestamp
  @Column(name = "update_date", nullable = false)
  private OffsetDateTime updateDate;
}
